set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "intel")
  set(FFLAGS "-qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
  set(SUPPORTS_CXX "TRUE")
  set(CFLAGS "-qno-opt-dynamic-align -fp-model precise -std=gnu99")
  set(CXX_LDFLAGS "-cxxlib")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-r8")
  set(FFLAGS_NOOPT "-O0")
  set(FIXEDFLAGS "-fixed")
  set(FREEFLAGS "-free")
  set(SCC "icc")
  set(SCXX "icpc")
  set(SFC "ifort")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(MPICC "mpicc")
  set(MPICXX "mpicpc")
  set(MPIFC "mpifort")
  set(NETCDF_PATH "$(EBROOTNETCDFMINFORTRAN)")
  set(PNETCDF_PATH "$(EBROOTPNETCDF)")
  set(MPI_PATH "$(MPI_ROOT)")
  set(MPI_LIB_NAME "mpi")
  set(PIO_FILESYSTEM_HINTS "lustre")
endif()
set(CPPDEFS "${CPPDEFS}  -DCESMCOUPLED")
if("${MODEL}" STREQUAL "pop")
  set(CPPDEFS "${CPPDEFS}  -D_USE_FLOW_CONTROL")
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(CPPDEFS "${CPPDEFS}  -DSPMD")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8)")
endif()
if("${MODEL}" STREQUAL "mom")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8) -Duse_LARGEFILE")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(FFLAGS "${FFLAGS}  -xavx2 -no-fma")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DCPRINTEL")
  set(CPPDEFS "${CPPDEFS}  -D$(OS)")
  set(SLIBS "${SLIBS} -mkl=sequential -lnetcdff -lnetcdf")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -qopenmp")
  endif()
  if("${MODEL}" STREQUAL "cice")
    set(FFLAGS "${FFLAGS}  -init=zero,arrays")
    set(FFLAGS "${FFLAGS}  -init=zero,arrays")
  endif()
  if("${MODEL}" STREQUAL "blom")
    set(FFLAGS "${FFLAGS}  -r8")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(CFLAGS "${CFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
    set(CFLAGS "${CFLAGS}  -O0 -g")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O2 -debug minimal")
    set(FFLAGS "${FFLAGS}  -O2")
    set(CFLAGS "${CFLAGS}  -O2 -debug minimal")
  endif()
  if("${MPILIB}" STREQUAL "mpich")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpich2")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mvapich")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mvapich2")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpt")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "openmpi")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "impi")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpi-serial")
    set(SLIBS "${SLIBS}  -mkl")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -qopenmp")
  endif()
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(INCLDIR "${INCLDIR}  -I$(EXEROOT)/atm/obj/FMS")
endif()
